function [options] = training_options(batchSize, lr, maxEpochs, VerboseFrequency)
% Configure training options.
%
% * Lower the InitialLearningRate to reduce the rate at which network
%   parameters are changed.
% * Set the CheckpointPath to save detector checkpoints to a temporary
%   directory. Change this to another location if required.
% * Set MaxEpochs to 1 to reduce example training time. Increase this
%   to 10 for proper training.
% * Faster-rcnn are train in 4 steps.
%
%{
options = trainingOptions('sgdm', ...
      'MiniBatchSize', batchSize, ...
      'InitialLearnRate', lr, ...
      'MaxEpochs', maxEpochs, ...
      'VerboseFrequency', VerboseFrequency, ...
      'CheckpointPath', tempdir);
%}
  % Options for step 1.
  
    optionsStage1 = trainingOptions('sgdm', ...
        'MaxEpochs', maxEpochs, ...
        'MiniBatchSize', batchSize, ...
        'InitialLearnRate', lr, ...
        'VerboseFrequency', VerboseFrequency, ...
        'CheckpointPath', tempdir);

    % Options for step 2.
    optionsStage2 = trainingOptions('sgdm', ...
        'MaxEpochs', maxEpochs, ...
        'MiniBatchSize', batchSize, ...
        'InitialLearnRate', lr, ...
        'VerboseFrequency', VerboseFrequency, ...
        'CheckpointPath', tempdir);

    % Options for step 3.
    optionsStage3 = trainingOptions('sgdm', ...
        'MaxEpochs', maxEpochs, ...
        'MiniBatchSize', batchSize, ...
        'InitialLearnRate', lr, ...
        'VerboseFrequency', VerboseFrequency, ...
        'CheckpointPath', tempdir);

    % Options for step 4.
    optionsStage4 = trainingOptions('sgdm', ...
        'MaxEpochs', maxEpochs, ...
        'MiniBatchSize', batchSize, ...
        'InitialLearnRate', lr, ...
        'VerboseFrequency', VerboseFrequency, ...
        'CheckpointPath', tempdir);

    options = [
        optionsStage1
        optionsStage2
        optionsStage3
        optionsStage4
        ];

end

